# Site settings
title: 龙吟的博客
SEOTitle: 龙吟的博客 | Loongyowl 
header-img: img/post-bg-desk.jpg
email: huangju7231@126.com
description: "loongyowl's blog, About philosophy, psychology, business management and digitization"
keyword: "joe黄的思考, Loonyowl, 龙吟的博客, Buddha, 龙吟, 企业管理, 心理学, NLP教练, 地产策划，营销策划，商业程序"
url: "http://loongyowl.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/loongyowl/loongyowl.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "明白江山烟花事 落叶任风添飘情"
sidebar-avatar: /img/huangju1.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:   loongyowl
zhihu_username:     joehuang331
github_username:    loongyowl
facebook_username:  loongyowl
jianshu_username:   9575d17160ef
#twitter_username:  loongyowl




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: b2c37b3cd9a2ba80f123                            #生成的clientID
  clientSecret: 52b72e651b942c70c319b7c28475500ead41d654    #生成的clientSecret
  repo: loongyowl.github.io    #仓库名称
  owner: loongyowl    #github用户名
  admin: loongyowl
  id: decodeURI(window.location.pathname).split("/").pop().substring(0, 49),
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 0ddcb555c2770268f6c4660246653ff6

# Google Analytics
ga_track_id: 'UA-164528890-1'            # Format: UA-xxxxxx-xx
ga_domain: loongyowl.com                 # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "格鲁修学社区",
        href: "http://www.gelupa.org/"
    },{
        title: "W3C·践行群中的思考",
        href: "https://w3c.group/g/1124570"
    },{
        title: "我的qq空间",
        href: "https://user.qzone.qq.com/315856601/main"
    },{
        title: "版权：CC BY-NC-ND 4.0",
        href: "https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh"
    }
]
